// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWEs0QaLVvkCIl99dKguGxMXD6XDilL4',
    appId: '1:839687124464:web:d545d300fff7f134661935',
    messagingSenderId: '839687124464',
    projectId: 'inclass17-93418',
    authDomain: 'inclass17-93418.firebaseapp.com',
    storageBucket: 'inclass17-93418.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4OodkJRMoJoHdp8cZ3dM_q1R6gQ3u-ME',
    appId: '1:839687124464:android:4cf982eca1856ce2661935',
    messagingSenderId: '839687124464',
    projectId: 'inclass17-93418',
    storageBucket: 'inclass17-93418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9K579qJU6Smcdne5GgRYGnvuX6ln14BU',
    appId: '1:839687124464:ios:25f448c7de39c9de661935',
    messagingSenderId: '839687124464',
    projectId: 'inclass17-93418',
    storageBucket: 'inclass17-93418.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9K579qJU6Smcdne5GgRYGnvuX6ln14BU',
    appId: '1:839687124464:ios:25f448c7de39c9de661935',
    messagingSenderId: '839687124464',
    projectId: 'inclass17-93418',
    storageBucket: 'inclass17-93418.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuWEs0QaLVvkCIl99dKguGxMXD6XDilL4',
    appId: '1:839687124464:web:09dcb7262a6bd5fe661935',
    messagingSenderId: '839687124464',
    projectId: 'inclass17-93418',
    authDomain: 'inclass17-93418.firebaseapp.com',
    storageBucket: 'inclass17-93418.firebasestorage.app',
  );
}
